server:
  port: 9090

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

module:
  song:
    enabled: true
    resources:
      song: /api/v1/song
      setlist: /api/v1/setlist
